name: Dashboard Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        echo 'Installing dependencies...'
        cd vue-paper-dashboard
        npm install

    - name: Build project
      run: |
        echo 'Building project...'
        cd vue-paper-dashboard
        npm run build
