name: Dashboard Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        echo 'Installing dependencies...'
        npm install

    - name: Build project
      run: |
        echo 'Building project...'
        cd vue-paper-dashboard
        npm run build
